### ISSUE TITLE
Can't seem to pass SSH keys to VM

### ISSUE THREAD

**Issue by jasonseminara** [nmische/vagrant-cfo-coldfire-dev#1]
I've been trying to get the VM to complete its provisioning, but it keeps getting hung up on the error below. I've followed all instructions provided, placed my keys in the node format and even created a data_bag, but the Vm can't seem to make a connection to github using my SSHkeys. The keys work perfectly from the host terminal. I've even tried manually copying the .ssh file into the VM... still nothing.

What is going wrong?

[2013-05-24T03:01:23+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: git[/vagrant/wwwroot/coldfire](coldfire-dev::default line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git ls-remote git@github.com:jasonseminara/ColdFire.git master ----
STDOUT: 
STDERR: Permission denied (publickey).
fatal: The remote end hung up unexpectedly
---- End output of git ls-remote git@github.com:jasonseminara/ColdFire.git master ----
Ran git ls-remote git@github.com:jasonseminara/ColdFire.git master returned 128
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by nmische** [comment]
You should place your private key in either the data bag or the Vagrantfile, but not both. 

If you `vagrant ssh` into the Vagrant VM, does /tmp/vagrant-chef-1/.ssh/id_deploy contain the correct private key? If so is /tmp/vagrant-chef-1/wrap-ssh4git.sh pointing to that file?

**Comment by jasonseminara** [comment]
I destroyed everything and restarted the whole process. I inserted my repo info:

# Put your ColdFire repo settings here.

```
  "coldfire-dev" => {
    "git" => {
      "repository" => "git@github.com:jasonseminara/ColdFire.git",
      "revision" => "master",
      "deployment_key" => "ssh-rsa AAAAB3Nza.....4s9t"
    }
  },
  ## # # # # # # # # # # # # # # # # # # # ##
```

Still the same error. Then it hit me! I was using the PUBLIC key in there. So I switched it to the private key (pbcopy < ~/.ssh/id_rsa)
vagrant reload 

Still the same error.
vagrant ssh: id_deploy is in place, contains the proper private key
/tmp/vagrant-chef-1/wrap-ssh4git.sh points to the file properly.

I then tried pinging yahoo from the VM... success (we have internet access).

vagrant@precise32:~$ ping yahoo.com
PING yahoo.com (98.139.183.24) 56(84) bytes of data.
64 bytes from ir2.fp.vip.bf1.yahoo.com (98.139.183.24): icmp_req=1 ttl=63 time=81.0 ms
64 bytes from ir2.fp.vip.bf1.yahoo.com (98.139.183.24): icmp_req=2 ttl=63 time=744 ms
^C
--- yahoo.com ping statistics ---
3 packets transmitted, 2 received, 33% packet loss, time 2190ms
rtt min/avg/max/mdev = 81.085/412.613/744.141/331.528 ms

Then a git request directly from the vm (no dice):
vagrant@precise32:~$ git ls-remote git@github.com:jasonseminara/ColdFire.git master
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

I know the key is valid because it works from the host.
myMac:coldfire jasonseminara$ git ls-remote git@github.com:jasonseminara/ColdFire.git master
Identity added: /Users/jasonseminara/.ssh/id_rsa (/Users/jasonseminara/.ssh/id_rsa)

Am I the only one having this problem?
